---
- name: Test ping
  hosts: all
  tasks:
    - name: Ping nodes
      ansible.builtin.ping:

    - name: create user
      user:
        name: user1
        shell: /bin/bash        
        uid: 1040 
...
